### ISSUE TITLE
recursion & big 2d array

### ISSUE THREAD

**Issue by ksanabuka** [Manmeet2018/42_Exam-C-Intermediate#1]
Hei Manmeet, the recursion can overgrows the stack memory if we use huge array ... Need safer solution :)) 
Really enjoy your coding style.

**Comment by genisis0x** [comment]
Hello Fellas,

Thanks for the feedback!!

I think the stack calls on recursion will grow only when there are valid cases as this problem can be divided into subproblems of same type then when this type of problems come the only strategy comes in the mind is Divide and Conquer approach to solve the problem.

Now coming to the point is this type of problem can be solved without using the inbuilt stack (Recursion approach) and the answer to the question is yes we can solve this problem iteratively and  can use your own stack but the issue in using the iterative method will be that to write it, it's so expansive as per the memory management point of view.

In worst case the Space Complexity will be the O(N *N) grid, So we can use iterative method + dynamic approach to solve the whole issue, i will try and post that approach solution to my Git repo in some time.

BR
Manmeet Parmar

**Comment by ksanabuka** [comment]
it sounds logically, agree.
